FROM node:20-alpine AS builder
WORKDIR /app
COPY jshERP-web/package.json ./
RUN npm install --legacy-peer-deps --registry=https://registry.npmmirror.com
COPY jshERP-web/ ./
RUN npm run build -- --report

FROM nginx:1.21-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
